### ISSUE TITLE
Generator doesn't seem to generate anything

### ISSUE THREAD

**Issue by draand28** [PolyhedralDev/BetterEnd#28]
I'm using Paper-247, with latest waterfall. 
I've been trying to use BetterEnd for my Survival server but I always get the original End world.
I don't think this is an only me issue but more like a general bug.
I'm providing here a log and my bukkit.yml.
Log: https://pastebin.com/36fP8QFN
Bukkit.yml: https://pastebin.com/N1sUtXga

**Comment by dfsek** [comment]
Did you reset your world?

**Comment by draand28** [comment]
Yes, every time I tried to re-generate "world_the_end" I deleted the world_the_end folder before starting up the server.

**Comment by dfsek** [comment]
Everything appears to be in order. What happens when you run `/be biome teleport AETHER` in the end?

**Comment by draand28** [comment]
Yep, it appears to work. It does indeed teleport me to a newly generated BetterEnd Biome. (1500 in X coords). 
Now I realise that only the End spawn is the same, if I move away by 1000 blocks from the basic End spawn, I'm getting new BetterEnd chunks (I dind't pre-generate the End yet because I didn't know if the generator worked fine). 
Should the BetterEnd spawn (coords x=0, y=0 aprox.) be the same as the basic End spawn (like with ender dragon, island, etc)? If yes, then I'm sorry for wasting your time, didn't know that.

**Comment by dfsek** [comment]
Yes, the main island is unchanged. Not much to change there.
