### ISSUE TITLE
Chunky DESTROYS Generation!!!!!

### ISSUE THREAD

**Issue by YTMrSnipa** [PolyhedralDev/BetterEnd#32]
So this happened
![image](https://user-images.githubusercontent.com/67626963/100552970-ca06ac80-32b0-11eb-80a6-7a752fe42652.png)

https://pastebin.com/2PfsnTH5

pls fix kthnx

**Comment by solonovamax** [comment]
1. please give steps to reproduce this
2. what plugins are you using

**Comment by dfsek** [comment]
A description of your environment in general is required, I don't know how you expect us to magically know exactly what is wrong.
* What plugins are you using
* Configuration files
* Server software

etc.

**Comment by YTMrSnipa** [comment]
Was just trying to pregenerate some chunks when this happened...
Using Chunky + BetterEnd
Server software is paper mc
Configuration Files of betterEnd:
https://pastebin.com/PJA8G1fV

**Comment by dfsek** [comment]
Still not very helpful. Upload your *world* configuration.
What Paper build?
What BetterEnd version?

("latest" is not a version)

**Comment by YTMrSnipa** [comment]
World Config:
https://pastebin.com/6dZG6KyY

Paper build git-Paper-288
BetterEnd Version BetterEnd v4.4.4-free

**Comment by dfsek** [comment]
![image](https://user-images.githubusercontent.com/39248502/100658495-64480e00-330c-11eb-930f-7c80cc7f8fc7.png)
There's your issue.

**Comment by YTMrSnipa** [comment]
Tysm
