### ISSUE TITLE
This world is not a betterend world

### ISSUE THREAD

**Issue by Faitywave** [PolyhedralDev/BetterEnd#34]
Hi my friend just downloaded this plugin post enderdragon beaten, we were about to teleport to the aether biome but than it says This world is not a better end world. we need help because i cant find a solution. Any help would be really nice, Thank You!

**Comment by dfsek** [comment]
Read the [installation instructions](https://github.com/PolyhedralDev/BetterEnd/wiki/Installation). You need to set the generator via `bukkit.yml`
